version: '0.0'

services:
  web:
    build: .
    restart: on-failure
    ports:
      - "5000:5000"
    expose:
      - 5000 
    environment:
      - WAIT_HOSTS=mariadb:3306, redis:6379
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    links:
      - redis
      - mariadb

  redis:
    image: "redis:alpine"
    ports:
      - "6379"
    volumes:
      - persistent_redis:/data

  mariadb:
    image: "mariadb:latest"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "admin"
      MARIADB_USER: "admin"
      MARIADB_PASSWORD: "admin"
      MARIADB_DATABASE: "db"
    volumes:
      - database_mariadb:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306"

volumes:
  database_mariadb:
    external: false
  persistent_redis:
    external: false
